davezuko/react-redux-starter-kit

build/webpack/make-config.js
karma.entry.js

`?` means optional, I think it was a copy-paste typo

fix(regex): typos

---

.eslintrc
build/webpack/make-config.js
config/index.js
package.json
src/containers/app.jsx
src/utils/index.js

cue taken from https://gist.github.com/tlrobinson/1e63d15d3e5f33410ef7

add option to use devtool in a new window to free space for actual app

---

README.md

This is probably obvious for most React devs but might not be so straightforward
to someone not used to a Node build process. Thoughts?

Add Getting Started section to Readme

---

config/index.js
package.json
src/containers/Root.js
src/index.js
src/reducers/index.js
src/routes/index.js
src/stores/index.js
src/views/HomeView.js

@davezuko two purposes here:
* Wanted to document how to switch over to redux router for anyone who is interested
* Wanted to make sure my suggested changes aren't breaking anything (please let me know!)
Thanks for your work here -- I'm switching from pure rails to rails api + react frontend and this has helped quite a bit.

Add Redux Router.

---

bin/webpack-dev-server.js

It can dynamic setting host in config file

Add Dynamic host in webpack-dev-server

---

src/layouts/CoreLayout.js

Removed trailing space to satisfy eslint

---

src/actions/counter.js
src/constants/counter.js
src/reducers/counter.js
src/views/HomeView.js

I did see the comments about this in the code but still thought it was a good idea. This helps on new projects when prototyping a store and reduces the clean up needed on a new project (removing the existing counter constants/actions).

Extracted counter constants and action creates in to dedicated folders

---

.editorconfig

added section to .editconfig

---

package.json

Adds cross-platform compatibility to npm scripts to fix issue #162

Implement better-npm-run

---

.travis.yml

Explanation:
https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/

Speed up Travis using caching

---

config/index.js

set `vendor_dependencies` with `validVendor`

use `validVendor`

---

src/views/HomeView.js
tests/views/HomeView.spec.js

I think as a starter project its a good idea to push people towards the more simple, but elegant use of the `connect` api from `react-redux`

Simplifies how action creators are passed to the HomeView

---

src/utils/index.js

This change allows us to write reducers which depend on additional data as described here: https://github.com/rackt/redux/issues/749#issuecomment-141570236

Improve createReducer

---

README.md
build/webpack/_base.js
config/index.js

Closes https://github.com/davezuko/react-redux-starter-kit/issues/241

feat(config): make CSS modules configurable

---

bin/compile.js
config/_production.js
config/index.js
server/middleware/webpack-dev.js

Resolves https://github.com/davezuko/react-redux-starter-kit/issues/267

feat(config): allow user to configure webpack stats output

---

.env
README.md
bin/compile.js
bin/server.js
build/karma.js
build/webpack/_base.js
build/webpack/_development.js
build/webpack/_production.js
config/_base.js
config/index.js
server/app.js
server/middleware/webpack-dev.js
server/middleware/webpack-hmr.js

updated #274, per discussion—resolves #273

refactor(debug): update kit namespace to app

---

package.json

fix(eslint): only apply semicolon fix to js files

---

src/redux/modules/counter.js
src/views/HomeView.js
tests/views/HomeView.spec.js

Resolves https://github.com/davezuko/react-redux-starter-kit/issues/255

feat(counter): add sample doubleAsync action

---

src/layouts/CoreLayout.js
src/views/AboutView.js
tests/layouts/CoreLayout.spec.js

Pure component notes

---

src/containers/Root.js
src/index.html
src/styles/_base.scss

Use getters in Root, add 100% height up to start of app content (the developer can take it from there), and some additional best-practice starter CSS rules.

Improve Root

---

build/webpack/_production.js

fix(config): Make css extract more flexible

---

build/webpack/_base.js

Nothing special, just the double quotes that hurt my :eyes:

Fixed double quote inconsistencies-webpack_base.js

---

build/webpack/_development.js

fix(config): Make babel plugin overrides more flexible

---

package.json

resolves #256, @neverfox @patrickheeney can you guys confirm?
https://phabricator.babeljs.io/T6644 resolved via https://phabricator.babeljs.io/rBCd2ee42194114e2350a0e8d55db78a74b720d8479

chore(babel): update dependencies

---

src/routes/index.js

Resolves https://github.com/davezuko/react-redux-starter-kit/issues/306

refactor(routes): define path before component

---

src/containers/Root.js

fixes https://github.com/davezuko/react-redux-starter-kit/issues/319

fix(DevTools): devtools in compile for production

---

README.md

... and add subtitle for ProvidePlugin within section "Provided Plugins"

Extend section about global variables with info about automatic imports

---

README.md

While compiling in "development" settings Sublime has a hard time parsing app.js file
```
worker 85850 appears stuck while processing file react-redux-starter-kit/dist/app.899b349b9005e200c0f4.js, killing process
```
as a solution exclude `dist` folder

High CPU usage Sublime

---

README.md
build/webpack-environments/_base.js
build/webpack-environments/production.js

Relative assets fix (fixes #357)

---

src/redux/utils/createDevToolsWindow.js

npm run dev:nw failed before this fix

fix(chore): devTools - add ReactDOM, React to devTools

---

build/webpack.config.js

refactor(webpack): allow mix of global and module CSS

---

src/redux/configureStore.js

fixes https://github.com/davezuko/react-redux-starter-kit/issues/503

fix(build): redux-devtools dead code removal

---

build/webpack.config.js
config/_base.js
config/_production.js
server/lib/apply-express-middleware.js
server/middleware/webpack-dev.js
server/middleware/webpack-proxy.js

Remove semicolon in webpack-proxy
Remove unused arguments

style(standard): minor linting

---

build/karma.conf.js

Fix test runner on Windows

---

README.md
build/webpack.config.js
package.json

Add some plugins for improving the production build.
| Name | Build size impact | Description |
|:-----|:-----|:------|
| [transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) *(Promoted)* | -0.3 kB | Remove `PropTypes`. | 
| [transform-react-constant-elements](https://babeljs.io/docs/plugins/transform-react-constant-elements/) | 0 kB | Save some memory allocation. |
| [~~transform-react-inline-elements~~](https://babeljs.io/docs/plugins/transform-react-inline-elements//) | ~~+0.7 kB~~ | ~~Improve runtime performances.~~ |

[Babel] Improve the production build

---

package.json

Upgrade of flow interfaces so dev dependencies are up to date (green status)

upgrade(flow-interfaces): ^0.4.0 -> ^0.5.0

---

build/karma.conf.js

fix(webpack/karma): add react/addons to externals

---

tests/test-bundler.js

Resolves https://github.com/davezuko/react-redux-starter-kit/issues/572

fix(karma): fix karma webpack manifest initializer

---

README.md

This addresses the issue https://github.com/davezuko/react-redux-starter-kit/issues/722
Before merging, I would really hope to get some feedback on the post from the people who *actually* know what this stuff is all about :)
In the meantime, I have learned a lot and really appreciate this starter-kit, so thanks!

Add learning resource: tutorial on how to get started with the starter kit

---

README.md

I just went through deploying it to Heroku and decided to document it for other people. @davezuko let me know if you want to make some changes or feel free to reject this ;)

Update Heroku deployment section

---

src/main.js

fix(main): specify .default property when importing RedBox using require()

---

README.md

This is a work in progress to fill in some gaps in the README.  Personally, I'd like to see the README be a place that gives you enough direction to know where and how to start adding code to your react-redux-starter-kit based project.  Now that the project has been moved to fractal, and some of the code resources have as well.. I have a few questions that would help me better understand where things are intended to go.  And, if worthwhile, I'll add any information to the README so that others can benefit.
Questions:
1. Currently, counter's presentational component is located at `src/components/Counter/*`, while its reducer and component wiring (container) is located at `src/routes/Counter/*`.  Conversely, the current skeleton (tree in README) demonstrates that …

[WIP] Exhanced documentation in README

---

.eslintrc
.gitignore

Added Intellij config folder to `.gitignore`
Added already isntalled plugins to `.eslintrc`

ESLint configuration

---

package.json

According to the README.md:
```
npm run deploy : Runs linter, tests, and then, on success, compiles your application to disk.
```

chore(package.json): deploy runs linter and test

---

package.json

fix(config): bumped eslint-promise dependency to meet requirements

---

package.json

<fix>Update package.json to include babel-core

---

src/routes/Counter/modules/counter.js

removed
> NOTE: This is solely for demonstration purposes. In a real application,
>     you'd probably want to dispatch an action of COUNTER_DOUBLE and let the
>     reducer take care of this logic
the change is not that big, and demonstrate what the pattern should be in a real application

Add COUNTER_DOUBLE_ASYNC action

---

config/webpack.config.js

I ran into an issue with this starter kit once my project became relatively large. The build step would never complete and would run forever, after days of debugging the simplest and most elegant solution was to add the AggressiveMergingPlugin.
It also speeds up my production deploy from 12 minutes to 3 minutes
Thanks

Add AggressiveMergingPlugin to Webpack config

---

src/main.js

fix(redux): fix store instantiation from __INITIAL_STATE__

---

package.json

I use windows machine,when I tried to build my app I had an issue with NODE_ENV.This changes fixed it.

fix(package.json): build script for windows env

---

build/webpack.config.js

fix(webpack): bug 1269, HMR fails on second update
