davezuko/react-redux-starter-kit

.eslintrc, build/webpack/make-config.js, src/constants/todo.js, src/reducers/todos/index.js, src/utils/create-constants.js, src/utils/create-reducer.js, src/utils/createConstants.js
This PR has 2 things:
- a `createConstants` utility function. Should save some typing when building a large application
- change the switch statement in the reducer to use a reducers map, keeps the actual function clean :).
Would love to hear your thoughts!
=> Suggestion: Some cleanup

.travis.yml
"iojs" is an alias for the latest stable version, which is currently 3.0, and with that version the project wouldn't run locally either.
=> This should allow Travis to build iojs.

build/webpack/client/index.js
Hi!
The require call was failing due to an extra space so, I just added a `.trim()`... :smile: 
This is my npm script that was raising the error (I'm on Windows right now):
`"deploy": "SET NODE_ENV=production && npm run test && npm run compile"`
Thanks!
=> Fix webpack client config

config/index.js
See https://github.com/davezuko/react-redux-starter-kit/pull/32.
=> fix(config): trim spaces from NODE_ENV to avoid problems on windows

.babelrc, package.json
The package `react-transform-webpack-hmr` was renamed to `react-transform-hmr`. This PR simply update the dependencies/scripts.
=> Use react-transform-hmr

build/webpack/_base.js, build/webpack/development.js
=> fix(webpack): do not generate source maps in production builds

build/webpack/development_hot.js
Updates react-transform HMR check to not match json-loader.
While trying to use the color-loader package, I ran into an issue with the react-transform HMR map function, matching when including the follow loader block:
```js
{
test: /\.json$/,
loader: 'json-loader'
}
```
Since I'm assuming it was only meant to match the babel loader.
Lastly, is there a reason you match on the test and not the loader prop?
Example: 
```js
if (/babel/.test(loader.loader)) { ... }
```
Seems to work as well?
Thanks
=> Ability to add json-loader

build/webpack/_base.js, package.json
Accomplishes the same thing as the specialized autoprefixer-loader, but now the kit is set up for the addition/configuration of other postcss plugins, as desired.
=> Use postcss-loader to plug in autoprefixer

README.md, config/index.js, package.json, src/app.js, src/containers/Root.js, src/reducers/index.js, src/routes/index.js, src/store/configureStore.js, src/views/AboutView.js, src/views/HomeView.js
resolves #196
includes minimal demo `/about` route with basic [stateless function component `AboutView`](https://github.com/justingreenberg/react-redux-starter-kit/blob/master/src/views/AboutView.js)
-
**screenshots**
click on **Go To About View** which is a react-router `Link` [component](https://github.com/davezuko/react-redux-starter-kit/pull/198/files#diff-def9b7b3e3020460b0cb272526a5877cR35)
`redux-simple-router` keeps the path [synchronized](https://github.com/davezuko/react-redux-starter-kit/commit/fc505bf464c650b5c81c549cbb3c4be7da77bf6e#diff-bd9c9dcd314f2d7df52935b3a6a4d504R12) with store
-
i think there's a some confusion about this library's scope and relationship with `react-router`, so it might be a good idea to include a link to the `redux-simple-router` ie. [How To …
=> (refactor)app: switch to redux-simple-router

src/store/configureStore.js
When debug mode is disabled by running "mpn run dev:no-debug", createStoreWithMiddleware function fails since its not initialized.
=> Fixed a breakage while creating the store

README.md
I was copy pasting some README elements to my own app's README and figured that the `styles` folder is left out in the *structures* part.
=> docs(readme): add styles folder

build/karma.js, karma.entry.js
I found that the tests will run twice when file changes occurs when the Karma is set to autoWatch. For more information, please check this out: https://github.com/nikku/karma-browserify/issues/67.
=> fix(karma): Avoid run tests twice when autoWatch is set to true

build/webpack/_base.js, src/app.js, src/containers/Root.js, src/redux/configureStore.js
i'm not sure when or how the plugin broke but this fixes es6 default export interop with commonjs and removes the `{ default }` hotfix for inline require statements
=> fix(babel): fix export interop, remove hotfix

CONTRIBUTING.md
this file will be picked up by github and encourages contributors to review before making pull requests... ie. using our commit message conventions
=> feat(project): add contributing guidelines

build/webpack/_base.js
Fixes https://github.com/davezuko/react-redux-starter-kit/issues/282
=> fix(webpack): run .css files through postcss-loader

src/index.html, src/styles/_base.scss
For some reason, the root class didn't "take" and the style approach feels cleaner since it's out of the way.
=> fix(app): fix root element style so that height 100% applies

src/redux/modules/counter.js
Resolves https://github.com/davezuko/react-redux-starter-kit/issues/322
=> fix(counter): use constant rather than string for action handler

src/layouts/CoreLayout.js, src/redux/utils/createDevToolsWindow.js, src/routes/index.js
resolves https://github.com/davezuko/react-redux-starter-kit/issues/307
=> refactor(imports): always use relative paths except in routes

src/containers/Root.js, src/redux/configureStore.js
This PR enables the use of the [redux-devtool-extension](https://github.com/zalmoxisus/redux-devtools-extension)  if available, instead of using redux-devtools-log-monitor/redux-devtools-dock-monitor.
PR #337 goes in that direction, but is a bit more complicated then necessary and produces a linter error. Also, it does not handle the "open devtools in new window" option correctly (I think one would expect that it to open redux-devtools-extension in a new window, not redux-devtools-log-monitor).
In redux-devtools-extension there is an option to open the extension programmatically (`window.devToolsExtension.open()`) which results in this: 
This is exactly the "npm run dev:nw" behavior, so if redux-devtools-extension is available, we'll use it.
The README should probably be updated too to …
=> feat(devtools): Use redux-devtools-extension if available

.eslintrc, README.md, build/webpack-environments/_base.js, config/_base.js, src/containers/DevTools.js, src/containers/DevToolsWindow.js, src/containers/Root.js, src/layouts/CoreLayout.js, src/main.js, src/redux/utils/createDevToolsWindow.js, src/routes/index.js, src/views/AboutView.js, src/views/HomeView.js, tests/layouts/CoreLayout.spec.js, tests/views/HomeView.spec.js
I really appreciate the effort that has gone into this project! It's been my goto to test new ideas and build a few projects.
Submitting this PR for review to reduce boilerplate. It uses webpack's ProvidePlugin to implicitly import React and ReactDom.
It also turns the `react-in-jsx-scope` rule off and makes React and ReactDOM globals.
=> chore(webpack): use ProvidePlugin to reduce boilerplate

build/webpack-environments/_base.js
I was including a local (woff-)version of the Roboto font using `@font-face` in core.scss, because [react-toolbox](https://github.com/react-toolbox/react-toolbox) requires it to be available. However, it would not be available, nor would the `@font-face` show up in the css file that is generated after running compile in an production environment.
Turns out, it's because of cssnano. It has some [*unsafe* options](http://cssnano.co/optimisations/), for example [postcss-discard-unused](https://github.com/ben-eb/postcss-discard-unused), which removes `@counter-style`, `@keyframes` and `@font-face`  if it does not find any usage of the declared keyframe/font/counter-style in the same file.
Since we're using css-modules, the usage of a declared font or animation is very likely *not* to be in …
=> fix(cssnano): Don't use unsafe cssnano options

.eslintrc, config/_base.js, package.json, src/main.js
A truly relative publicPath and the ability to configure a base path for React Router helps when deploying app in environments where its not served from the root path of the web server. The combination of changes lets you put the app arbitrarily deep, while still successfully serving resources and keeping route definitions defined in terms of '/'.
=> Make publicPath truly relative and configure history for basename

build/karma.conf.js
For some reason an npm package was getting included in my coverage reports.  Adding this `exclude` made it stop running coverage on the npm package.  The package was `js-cookie` in case you were wondering.  Not sure if this is actually a necessary PR or if I was just doing something silly in my code.
=> fix: remove node_modules from the coverage report

build/karma.conf.js, package.json
All the errors and failed tests of Karma reference just to the `test-bundler.js` and I think that's so useless information for a developer that I consider it a bug. For example:
```
(View) Home
✓ Should render as a <div>.
✗ Should include an <h1> with welcome text.
Error: Did not find exactly one match for tag:h1
at /Library/xxxxx/react/tests/test-bundler.js:48953
at /Library/xxxxx/react/tests/test-bundler.js:31020
```
I was able to fix that using `karma-sourcemap-loader` and now the output looks like this:
```
(View) Home
✓ Should render as a <div>.
✗ Should include an <h1> with welcome text.
Error: Did not find exactly one match for tag:h1
at /Library/xxxxx/react/tests/test-bundler.js:48953 <- webpack:///~/react/lib/ReactTestUtils.js:206:
at …
```
=> fix(karma): add sourcemap to get better references

README.md, config/_base.js
- Was not clear to beginner why new webpackDefine globals were not available in source. Add comment to `config/_base.js`
- Update README globals section.
=> docs(globals): Clarify globals must also be added to .eslintrc, update README

build/webpack.config.js
I'm using react-redux-starter-kit with django (utilising [django-webpack-loader](https://github.com/owais/django-webpack-loader) and [webpack-bundle-tracker](https://github.com/owais/webpack-bundle-tracker)) and the requests for `__webpack_hmr` fail because they are being attempted relatively.
=> Load HMR using public rather than relative path.

package.json, src/main.js
in main.js, if you use createHistory, you cannot use [recommended practices](https://github.com/rackt/react-router/blob/latest/docs/guides/NavigatingOutsideOfComponents.md) for transitioning routes via global browserHistory singleton.
Solves issue https://github.com/rackt/react-router/issues/3062
=> update react-router to 2.0.0, user browserHistory

package.json
This ensures `npm run clean` and `npm run deploy` runs on Windows
=> chore(windows): use rimraf instead of rm -Rf

bin/server.js
This small change makes the link clickable in some terminal emulators (like xfce-terminal), which makes it easier to open the app in a browser.
=> Made the app link clickable

src/main.js, src/redux/configureStore.js
```
// Dispatch from anywhere like normal.
store.dispatch(push('/foo'))
```
=> fix(config): make Redux actions work with store

.reduxrc, README.md, blueprints/blueprint/files/blueprints/__name__/files/.gitkeep, blueprints/blueprint/files/blueprints/__name__/index.js, blueprints/blueprint/index.js, blueprints/duck/files/__root__/redux/modules/__name__.js, blueprints/duck/files/__test__/redux/modules/__name__.test.js, blueprints/duck/index.js, blueprints/dumb/files/__root__/components/__name__.js, blueprints/dumb/files/__test__/components/__name__.test.js, blueprints/dumb/index.js, blueprints/form/files/__root__/forms/__name__Form.js, blueprints/form/files/__test__/forms/__name__Form.test.js, blueprints/form/index.js, blueprints/layout/files/__root__/layouts/__name__Layout/__name__Layout.js, blueprints/layout/files/__test__/layouts/__name__Layout.test.js, blueprints/layout/index.js, blueprints/smart/files/__root__/containers/__name__.js, blueprints/smart/files/__test__/containers/__name__.test.js, blueprints/smart/index.js, blueprints/view/files/__root__/views/__name__View/__name__View.js, blueprints/view/files/__test__/views/__name__View.test.js, blueprints/view/index.js
By putting blueprints inside the starter kit it allows users to easily find and override the templates to their teams specific needs.  As the starter kits conventions change and evolve the blueprints can be updated internally as well therefore eliminating the need for me to always be up to date with what's going on in the starter kit.
Let me know if you need any more explanation from me as far as what this PR is doing or if I messed up any of the contributing conventions!
Cheers
=> Adds redux-cli blueprints to starter kit

package.json
=> fix(eslint): pin eslint to ~2.2.0 to avoid missing estraverse-fb

config/_production.js
Building the project with the production configuration outputs an html file with the js and css linked as relative urls and if you have subpaths in your app, then anyone arriving at a subpath first will fail to find the resources as it will look for them in that subpath on the server.
=> fix(prod-config): use absolute paths in webpack's output

package.json, server/main.js
=> koa-static 3.x now supports koa2, so we don't need to convert anymore

package.json
The command `nodemon --exec node bin/server` does not start the server. Instead it shows the wrong usage of the `nodemon` command. Moreover, nodemon is a node wrapper, so it's not needed to call node as external program.
=> fix(nodemon): nodemon mustn't exec node to start the server

src/routes/Home/components/HomeView.js
Awesome starter kit..love the structure!  This tripped me up a bit at first, because I assumed CSS modules were being used..it looks like you just had some remnants of its use before it was deprecated from the webpack config.
=> fix(home component): remove implied use of CSS modules (deprecated)

src/containers/AppContainer.js, src/main.js, src/store/createStore.js, src/store/location.js, src/store/reducers.js, tests/store/createStore.spec.js, tests/store/location.spec.js, tests/test-bundler.js
cleaned up #1012 — resolves #1011 with simple `location` reducer (broken out into separate module and tested) that effectively keeps location in sync with store and works with HMR
known limitations...
- **will not** replay in address bar during time travel debugging
- **will not** respond to `LOCATION_CHANGE` events, other than to update the state... history actions should be made using `browserHistory` singleton or ie using `withRouter` HOC
these limitations can be mitigated using middleware, if necessary
=> feat(core): init store with sync location reducer

build/webpack.config.js
This PR corrects #863 where if a syntax error is encountered in tests,
the process throws an error during compilation. Tests are never run and
CI builds should now fail if there are syntax errors. This is done by
adding a small webpack plugin that checks for errors during compilation,
and adds them to an array of errors. This array is then thrown but only
if there are errors during the compilation stage.
Based on the suggestions from:
https://gist.github.com/Stuk/6b574049435df532e905
=> <fix>(webpack) Throw compliation errors

README.md
blueprint was deprecated in [this commit](https://github.com/davezuko/react-redux-starter-kit/commit/b2756be3fd0a96d3ff0f689689969cd4273246a3).
=> docs(readme): remove blueprint from application structure

src/main.js, src/store/createStore.js
`window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__` and `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.
See: zalmoxisus/redux-devtools-extension#220
=> chore(reduxDevTool): update reduxDevTools to use new api

src/routes/index.js
The point of CoreLayout/index.js is to import it instead of CoreLayout.js right?  It is CoreLayout.js's container.
=> Changed import of CoreLayout in route index

package.json, src/containers/AppContainer.js, src/layouts/CoreLayout/CoreLayout.js, src/routes/Counter/components/Counter.js
Addresses API changes in latest React API, where `PropTypes is deprecated.
https://github.com/facebook/react/blob/master/CHANGELOG.md#1550-april-7-2017
and fixes: https://github.com/davezuko/react-redux-starter-kit/issues/1216
=> Use prop-types npm module
